Added test for searching project on Projects list page
qa-guru/allure-testops-tests pull request #11
Opened 2021-08-25 21:35 UTC by AndreyKolesinskiy

User can search project on Projects list page:
1. Open Projects list page
2. Enter project name in Search field

ER: Project is displayed in search results

2021-09-02 18:20 UTC, svasenkov requested changes

2021-09-02 18:20 UTC, svasenkov commented on src/test/java/cloud/autotests/pages/ProjectsTable.java
> +    public ProjectsTable enterValueInSearchField(String searchValue) {
1. нет `@Step`
2. переименовать метод, setSearchValue / searchProject

2021-09-02 18:20 UTC, svasenkov commented on src/test/java/cloud/autotests/pages/ProjectsTable.java
> +    public ProjectsTable checkThatListOfProjectsContainsProject(String projectName) {
`@Step`

2021-09-02 18:20 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/ProjectsListTests.java
> +        step("Enter project name in Search field", () ->
вынести step в `Step` в пейджобъекты

2021-09-06 07:30 UTC, AndreyKolesinskiy commented
Updated according to comments

2021-09-06 07:30 UTC, AndreyKolesinskiy commented on src/test/java/cloud/autotests/pages/ProjectsTable.java
> +    public ProjectsTable enterValueInSearchField(String searchValue) {
Updated

2021-09-06 07:30 UTC, AndreyKolesinskiy commented on src/test/java/cloud/autotests/pages/ProjectsTable.java
> +    public ProjectsTable checkThatListOfProjectsContainsProject(String projectName) {
Updated

2021-09-06 07:31 UTC, AndreyKolesinskiy commented on src/test/java/cloud/autotests/tests/ProjectsListTests.java
> +        step("Enter project name in Search field", () ->
Updated

2021-11-19 18:01 UTC, dtuchs approved these changes

2022-03-29 05:44 UTC, sashkir7 commented
Данный функционал реализован в https://github.com/qa-guru/allure-testops-tests/pull/39

2022-03-29 05:44 UTC, closed without merging