added creation of Test Case test
qa-guru/allure-testops-tests pull request #12
Opened 2021-08-29 21:40 UTC by rocketby

**Preconditions**
- User is logged in Allure testOps
- Project with specified name already exists

**Actions**
1. Open project with specified name
2. From Sidebar navigate to Test Cases Table
3. Unlock test cases menu tree
4. Create new test case with unique name

**Asserts**
- Check, that number of test cases increased by 1 in test cases table
- Check, that test case with specified unique name is displayed in tese cases table 

5. Delete the created test case:
  5.1. Choose the test case
  5.2. Click bulk operations button
  5.3. Choose delete option
  5.4. Confirm deletion of the test case

2021-09-02 18:30 UTC, svasenkov requested changes

2021-09-02 18:30 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/TestCasesTests.java
> +    Timestamp timestamp = new Timestamp(System.currentTimeMillis());
унести в RandomUtils или Faker

2021-09-02 18:30 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/TestCasesTests.java
> +    private String testCaseName = "Test0001_Tat_"+timestamp.getTime(); //generate unique name of TC each time
пробелы до и после +

2021-09-02 18:30 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/TestCasesTests.java
> +        step("Unlock test cases menu tree", () -> {
дублируется степ - в тесте и в PO

2021-09-02 18:30 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/TestCasesTests.java
> +        step("Check, that new test case is displayed in test cases table", () -> {
убрать степы, тоже

2021-09-04 09:15 UTC, rocketby commented on src/test/java/cloud/autotests/tests/TestCasesTests.java
> +    Timestamp timestamp = new Timestamp(System.currentTimeMillis());
fixed

2021-09-04 09:18 UTC, rocketby commented on src/test/java/cloud/autotests/tests/TestCasesTests.java
> +    private String testCaseName = "Test0001_Tat_"+timestamp.getTime(); //generate unique name of TC each time
fixed

2021-09-04 09:18 UTC, rocketby commented on src/test/java/cloud/autotests/tests/TestCasesTests.java
> +        step("Unlock test cases menu tree", () -> {
fixed

2021-09-04 09:18 UTC, rocketby commented on src/test/java/cloud/autotests/tests/TestCasesTests.java
> +        step("Check, that new test case is displayed in test cases table", () -> {
fixed

2021-09-06 18:53 UTC, merged