add test Properties TestCase
qa-guru/allure-testops-tests pull request #13
Opened 2021-09-01 18:18 UTC by SBorisoglebsky

add test Properties TestCase
1. Open New TestCase
2. Check size in pane TestCaseOverview__secondary
3. Check property name at PaneSection__name

+ fix bug in test testcaseListDisplayedAfterNavigateBySidebar - expected size = 13

2021-09-02 18:44 UTC, svasenkov requested changes

2021-09-02 18:44 UTC, svasenkov commented on src/test/java/cloud/autotests/pages/TestProperties.java
> +
убрать перенос

2021-09-02 18:44 UTC, svasenkov commented on src/test/java/cloud/autotests/pages/TestProperties.java
> +    public void shouldHaveElement(String itemName) {
добавить `@Step`

2021-09-02 18:44 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/TestPropertiesTest.java
> +        $$(".LoadableTree__view > li").findBy(text("New")).click();
убрать в PO

2021-09-02 18:44 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/TestPropertiesTest.java
> +        testProperties.shouldHaveSize(8);
так 10 или 8 ?

2021-09-02 18:44 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/TestPropertiesTest.java
> +        testProperties.shouldHaveElement("Tags");
убрать в enum

2021-09-02 18:44 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/TestPropertiesTest.java
> +
убрать пустые строки

2021-09-04 17:18 UTC, SBorisoglebsky commented on src/test/java/cloud/autotests/tests/TestPropertiesTest.java
> +        testProperties.shouldHaveSize(8);
8, оставшиеся 2 избыточны в рамках логики теста.
Убрал

2021-09-06 18:45 UTC, merged