Create test cases for defect lyfe cycle
qa-guru/allure-testops-tests pull request #23
Opened 2021-10-17 15:47 UTC by SaleevaMariia

5 test cases for defects:
-create defect
-rename defect
-change description
-delete defect
-change status of defect

also was fix problems this another tests, related to changes in AllureTestOps site

authentification API is broken, so I temporary use a stub to fix it: all authentification goes thought UI

2021-11-19 17:54 UTC, dtuchs requested changes
В целом мне очень понравился PR!

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/models/Defect.java
> +        Faker faker = new Faker();
Это лучше вынести в статическое поле

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/models/Defect.java
> +    public Defect(){
code style (reformat code)

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/models/Defect.java
> +        Faker faker = new Faker();
!

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/models/Defect.java
> +        Faker faker = new Faker();
!

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/pages/defects/DefectInformation.java
> +    public void checkDefectName (String expectedName){
code style по всему бранчу, пожалуйста

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/pages/defects/DefectsPage.java
> +    public DefectsPage(){
конструктор всегда идет первым посде полей, но в данном случае он вообще не нужен - лучше сразу написать 
```
 private DefectsList defectsList = new DefectInformation();
    private DefectInformation defectInformation = new DefectsList();
```

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/pages/defects/DefectsPage.java
> +        defectInformation = new DefectInformation();
Если в конструкторе они проинициализированы, то, не очень понятно, зачем здесь второй раз?

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/defect/LifeCycleDefectTests.java
> +        defectsPage.getDefectInformation().changeStatus();
тут если бы не было коммента на русском, не понятно, почему будет closed
```
defectsPage.getDefectInformation().changeStatus(CLOSED);
```
или
```
defectsPage.getDefectInformation().changeStatusToClosed();
```

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/defect/LifeCycleDefectTests.java
> +
тут совсем не очевидно, что `generateNewDescription()` приведет к смене возвращаемого значения из геттера `getDescription()`

2021-11-19 17:54 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/defect/LifeCycleDefectTests.java
> +
аналогично, лучше использовать setName(...) т к не очевидно, что вызов `generateNewName()` будет иметь такие последствия

2022-03-30 18:03 UTC, sashkir7 commented
Добрый вечер!
Отличная работа - большое спасибо!

Немного доработал Ваш код и залил в рамках дочернего PR.

2022-03-30 18:10 UTC, merged