1. Update TagTest
qa-guru/allure-testops-tests pull request #27
Opened 2021-10-30 18:03 UTC by Suburbanknight89

1. Авторизуясь  в allure-testOps, заходим в проект gost-group.
2. Кликая по дашборду, переходим в тест-кейсы.
3. Выделяем все тесты и создаем для них новый тег (используя библиотеку фейкер для параллельного запуска)
4. Проверяем, что новый тег присвоился
5. Выделяем все тесты и удаляем ранее присвоенный тег.
6. Проверяем, что тег удалился.

2021-11-16 16:53 UTC, Amidosha commented
Большинство локаторов кажутся динамическими

2021-11-19 17:20 UTC, dtuchs requested changes

2021-11-19 17:20 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/AddTagTest.java
> +	void AddNewTagAndDeleteAfterAssertion() {
С маленькой буквы.

2021-11-19 17:20 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/AddTagTest.java
> +			$(".css-1hwfws3").click(); //клик на меню ввода текста
Такие css стили с _большой долей вероятности_ при редеплое изменят имя.

2021-11-19 17:20 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/AddTagTest.java
> +			$(".TreeNodeName", 5).click();
не очень понятно что означает 5 (magic number)

2021-11-19 17:20 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/AddTagTest.java
> +		});
Стэп называется assert, но в коде не ни одной проверки.

2021-11-19 17:20 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/AddTagTest.java
> +			$(".Menu__item:nth-child(11)").click();
грустный селектор - 11 элемент завтра станет 12-м или 10-м - если есть хоть какая-то возможность сделать лучше, то лучше сделать.

2021-11-19 17:20 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/AddTagTest.java
> +			$(".css-1hwfws3").click(); //клик на меню ввода текста
аналогично про css стиль (выше)

2022-03-29 13:07 UTC, merged