added test on a deletion of a newly created project
qa-guru/allure-testops-tests pull request #3
Opened 2021-08-18 16:11 UTC by vklonin

added the test: "checking project deletion process", 
menu items enum extended with item "SETTINGS", 
ProjectTable added a public variable with list size.

Test-case description:

> **Preconditions**

- user logged in to the allure.testOps
- new project with **known** name is created

> **Actions**

- From the project page navigates in Sidebar to Settings
- Push delete button and confirm a deletion

> **Assert**

- Search for the project by **known** name
- Ascertain that the project list after this search is empty

2021-09-02 17:19 UTC, svasenkov requested changes

2021-09-02 17:19 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/ProjectTestsDynamic.java
> +        String projectName = "testuser-testproject-toBeDeleted";
добавить рандомное имя, java faker / RandomUtils

2021-09-02 17:19 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/ProjectTestsDynamic.java
> +        String projectAbbr = "TD";
naming

2021-09-02 17:19 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/ProjectTestsDynamic.java
> +             $$("button.Button_style_success").find(Condition.text("New project")).click());
упростить

2021-09-02 17:19 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/ProjectTestsDynamic.java
> +            sidebar.navigateTo(MenuItem.SETTINGS);
это не PO феншуй

2021-09-02 17:19 UTC, svasenkov commented on src/test/java/cloud/autotests/pages/ProjectsTable.java
> +    public int size;
убрать либо в метод checkTableSize(Integer size) {

}

2021-09-06 13:13 UTC, closed without merging

2021-09-06 13:14 UTC, vklonin commented
Перепишу все под PO с учетом замечаний