Change of theme
qa-guru/allure-testops-tests pull request #6
Opened 2021-08-22 16:07 UTC by fuezl

Тест на смену темы оформления
1. Открываем главную страницу TestOps
2. Проверяем что отображается светлая тема оформления
3. Нажимаем на меню пользователя
4. Нажимаем Dark Mode
5. Проверяем что отображается тёмная тема оформления

2021-09-02 17:53 UTC, svasenkov requested changes

2021-09-02 17:53 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/ThemeTests.java
> +                assertThat(localStorage().getItem("AS_THEME")).isEqualTo("light"));
Нужно проверить стили у html тега

2021-09-02 17:53 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/ThemeTests.java
> +                $(".UserMenu__menu .Menu__item", 4).click());
уйти от индексов

2021-09-06 19:08 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/ThemeTests.java
> +    private void preparingLocalStorage(String theme) {
move to LocalstorageHelper

2021-11-19 18:09 UTC, dtuchs reviewed
Необходимо разрезолвить конфликты и можно мержить

2022-03-28 06:16 UTC, sashkir7 commented
PR закрыт в рамках https://github.com/qa-guru/allure-testops-tests/pull/33

2022-03-28 06:16 UTC, closed without merging