added SignOutTests (afterSignOutPageShouldContainValidDataTest)
qa-guru/allure-testops-tests pull request #7
Opened 2021-08-23 21:13 UTC by AnnRidel

2021-09-02 18:00 UTC, svasenkov requested changes

2021-09-02 18:00 UTC, svasenkov commented on src/test/java/cloud/autotests/tests/SignOutTests.java
> +            $(By.name("username")).shouldHave(attribute("placeholder", "Username"));
эти проверки можно вынести в AuthorizationPageTests.checkBaseElements()

2021-11-19 18:06 UTC, dtuchs requested changes

2021-11-19 18:06 UTC, dtuchs commented on src/test/java/cloud/autotests/tests/SignOutTests.java
> +    @Story("SignOut tests")
Имелось ввиду что сам класс и аннотация над ним НЕ должны быть отделены табуляцией :)

2022-03-28 08:10 UTC, closed without merging

2022-03-28 08:10 UTC, sashkir7 commented
PR закрыт в рамках https://github.com/qa-guru/allure-testops-tests/pull/35