add launchesPageShouldOpenAfterClickLaunchesBtn test
qa-guru/allure-testops-tests pull request #8
Opened 2021-08-25 08:32 UTC by avadanilov

2021-09-02 18:05 UTC, dtuchs requested changes

2021-09-02 18:05 UTC, dtuchs commented on src/test/java/cloud/autotests/pages/ProjectsTable.java
> +        $(".ProjectCard").$(".ProjectCard__links").$(".ProjectCard__link", 2).click();
Подумать как сделать лучше

2021-09-02 18:05 UTC, dtuchs commented on src/test/java/cloud/autotests/pages/ProjectsTable.java
> +        $(".ProjectCard").$(".ProjectCard__links").$(".ProjectCard__link", 2).click();
`a[href*="launches"]`

2022-03-28 08:30 UTC, sashkir7 commented
Плохая проработка добавляемого теста.

Для страницы Launches в дальнейшем необходимо добавить ряд тестов на проверку всего функционала, а не только тот факт, что в header страницы отображается слово header. Считаю, что данный тест практически бесполезен.

2022-03-28 08:30 UTC, closed without merging